### ISSUE TITLE
MethodNotAllowedHttpException

### ISSUE THREAD

**Issue by stevencsw777** [stephenafamo/laravel-2fa-starter#1]
When I accidentally enter the wrong OTP, i was redirected back to the same OTP page to enter the one time password again. When I enter the correct OTP, the system throw an error message. 

The Error 
(1/1) MethodNotAllowedHttpException
--

**Comment by mikewuerfel** [comment]
Yes, I can confirm this issue

**Comment by stephenafamo** [comment]
Okay, I'll check it out

**Comment by stephenafamo** [comment]
This is fixed now
